### ISSUE TITLE
Create stable version of I2C core

### ISSUE THREAD

**Issue by hiddemoll** [clash-lang/clash-compiler#2708]
The I2C core moved from the examples to Clash-Cores as an `Experimental` module. There are a few things which we want to do before promoting it from its experimental state. 

## TODO
- [ ] Expose debug flag of both I2C unittest subcomponents (Config.hs, Slave.hs)
- [ ] Add tests for smaller portions of the I2C core
- [ ] Refactor code to be more uniform  
- [ ] Move files from Experimental subdir
